### ISSUE TITLE
FlgihtDate previous years parsing bug

### ISSUE THREAD

**Issue by glebmachine** [georgesmith46/bcbp#5]
When you parse bcbp with previous year, it return `flightDate` as `2020-19-10` instead of `2018-10-19`

Test data:
`M1CHERNYAVSKAYA/ALEXANEKC7TUE SINDPSSQ 0938 293Y055K0210 362>5180  8292BSQ 06184761750012A61824252801290 SQ                        N*30602027K0E              `

Parsing results:
![image](https://user-images.githubusercontent.com/1610882/82674180-984ec200-9c4b-11ea-9a3a-60a794ed005c.png)

As you can see, flightDate should based on year from `issuanceDate`

**Comment by glebmachine** [comment]
Also, this bug affects date of month and month due to leap year

**Comment by georgesmith46** [comment]
It looks like this is because the issuance date format accepts the last digit of the year (**8**292), allowing it to have a more accurate estimate. The flight date on the other hand doesn't accept this format and therefore it has to assume the current year.

I can change this so you can force the estimated year. For example:
```js
decode("M1...", 2018)
```

Another option is to assume the same year as the `issuanceDate`, but since this is a conditional field it won't be reliable.

**Comment by georgesmith46** [comment]
For now, I've changed it to assume the issuance year as the same year for the flight date.

**Comment by glebmachine** [comment]
It works! 
Thank you for your quick feedback!!

**Comment by glebmachine** [comment]
@georgesmith46 
Still experiencing wrong year


Here is an example of bcbp code, contains flight with date `2020-09-02`, but, it decodes as `2021-09-02`
Here is a repro: https://stackblitz.com/edit/js-1x1gxt?file=index.js

**Comment by georgesmith46** [comment]
This is because it has to assume the current year for flight dates since this field contains only the day of year. I've attempted to fix this in #43
